# Numpy Basics

## Create Arrays

In [1]:
import numpy as np

In [3]:
# create an array from an existing list

list1 = [2, 7.5, 8, 9, 11]

arr1 = np.array(list1)

arr1

array([2. , 7.5, 8. , 9. , 11.])

In [5]:
# Check the dimension of arr1
arr1.ndim

1

In [6]:
list2 = [ [1,2,3,4],
          [5,6,7,8]]

arr2 = np.array(list2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2.ndim #returns the dimension of arr2

2

In [8]:
arr2.shape # It returns the shape of the arr2 as (m, n) where m: number fo rows, and n: number of columns.

(2, 4)

In [9]:
 # check the data type of the array

arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int64')

In [11]:
# Create an array with a specific data type
arr3 = np.array([2,3,4])

arr3.dtype

In [12]:
arr3

array([2, 3, 4])

In [14]:
arr4 = np.array([2,3,4], dtype="float64")

arr4.dtype

dtype('float64')

In [15]:
arr4

array([2., 3., 4.])

In [16]:
# Create an array with zeros

arr5 = np.zeros(8) # It will return a one-dimensioanl array with 8 zeros

arr5

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
# Create a 2-dimensioanl array of shape (m, n) with zeros

arr6 = np.zeros((3,4)) # it returns a array of shape (3,4) with zeros

arr6

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
# np.arange () it's similar to range() in list

np.arange(10) # it returns an array of elements from 0 to 9, 10 elements in total

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# nparange() generates an arithmetic sequence by indicating the start, stop and step.

np.arange(-3, 5, 0.5)

# It returns an arithmetic sequence starting with -3, and common difference d = 0.5, it stops before 5 (5 is not included)

array([-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
        2.5,  3. ,  3.5,  4. ,  4.5])

In [22]:
# np.arange() the default tep is 1 if not specified.

np.arange(-3,5)

# It will return an arithmetic sequence from -3 to 4 by common different d = 1 (default)

array([-3, -2, -1,  0,  1,  2,  3,  4])

## 2. Operations between Arrays

In [1]:
import numpy as np

In [4]:
arr1 = np.arange(1, 9).reshape((2,4))

arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
np.arange(1, 9)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [6]:
np.arange(1, 9).reshape((2,4))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
arr2 = np.arange(8).reshape((2,4))

arr2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [8]:
arr1 + arr2

array([[ 1,  3,  5,  7],
       [ 9, 11, 13, 15]])

In [9]:
# array multiplication: element-wise multiplication

arr1 * arr2

array([[ 0,  2,  6, 12],
       [20, 30, 42, 56]])

In [10]:
1/arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.2       , 0.16666667, 0.14285714, 0.125     ]])